version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 8000:8000
    depends_on:
      - mariadb
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mariadb:
    image: mariadb:11.3
    restart: always
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  mariadb-data:
  redis-data:
